# Generated by Django 4.2.6 on 2023-11-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0002_gadgetpost_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadgetpost',
            name='buy',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='購入場所'),
        ),
        migrations.AlterField(
            model_name='gadgetpost',
            name='map',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='マップ'),
        ),
    ]
